[package]
name = "vss-client"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = "0.11.6"
reqwest = { version = "0.11.13", features = ["rustls-tls"] }

[build-dependencies]
prost-build = { version = "0.11.3" }
reqwest =  { version = "0.11.13", features = ["blocking"] }

[dev-dependencies]
mockito = "0.31.1"
tokio = { version = "1.22.0", features = ["macros"]}

[features]
genproto = []
