[package]
name = "vss-accessor"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]

[dev-dependencies]

[build-dependencies]
prost-build = { version = "0.11.3" }
reqwest =  { version = "0.11.13", features = ["blocking"] }

[features]
genproto = []